evervault/evervault-node

README.md

making node readme consistent with docs

update node readme

---

package.json

Release version 1.1.9
Version update

Update version for release

---

package.json

Resync with released version number and reduce size of release bundle
- Update version number
- Release patch
- Restrict release bundle to lib directory

release new version

---

.github/workflows/release.yml

Invalid yaml syntax in release workflow
Fix indentation

fix: invalid yaml syntax

---

README.md

Outbound Relay is working in Node SDK so telling people how to use it
```javascript
const evervaultClient = new Evervault('<API-KEY>', { relay: true });
```

Update README to include Outbound Relay instructions

---

LICENSE

Commits need to be of the form `feat(X): ...` so that they will be automatically released

Release latest version

---

lib/config.js
lib/core/http.js
tests/config.test.js

Add CA host override via env var config

feat(ca-config-override): Add support for ca host config overrides

---

lib/index.js

Did not trigger release
Trigger with small spacing change.
We use [semantic-release](https://github.com/semantic-release/semantic-release#how-does-it-work) for deployments. If one of your commits should be deployed, ensure the commit message is in the format corresponding to the correct release type. This can also be done in a squash commit.
Note: breaking changes should always use the `BREAKING CHANGE:` commit message format.

fix(relay): triggering release

---

lib/index.js
lib/utils/proxyAgent.js
package-lock.json

Adding certificate validation
Added some methods for each request to validate the need of a certificate refresh

Adding certificate validation

---

README.md
lib/index.js
tests/client.test.js

The decryptionDomains option now supports wildcard domains
Add a short description about this PR.
Add links to issues, tech plans etc.

feat(outbound): supports wildcard domains

---

README.md
lib/core/http.js
lib/index.js
lib/utils/index.js
lib/utils/validationHelper.js
tests/core/http.test.js

Adding createRunToken function
Added function to retrieve token from api

feat(createruntoken): adding createRunToken

---

package-lock.json

Release broken as package-lock is not sync'd
- Sync package-lock

chore: auditing dependencies

---

README.md

There is some duplicate/deprecated content in the README.
The duplicated/deprecated content has been removed.

fix: README.md improvements

---

package-lock.json

The package-lock.json file was deleted in a previous PR.
I generated a new package-lock.json

fix: fixes the CI by re-adding package-lock.json

---

lib/core/crypto.js
lib/core/http.js
lib/index.js
tests/core/crypto.test.js

Need to be able to encrypt files for the upcoming File Encryption product
Added logic to check if data being passed to the encrypt function is a buffer, if so it encrypts it using our File Encryption scheme.

Implement file encryption

---

.github/workflows/test.yml
module.d.ts
package.json

i wanted to use evervault with ts but couldnt due to missing types. so, i made a declaration file. i dont know if it works when you try to import the module upon installation from npm but i run a few quick tests locally by importing it directly from the fs and it went smoothly
I wanted to use Evervault with ts
I made a simple declaration file, and used the docs to type the file

feat(module.d.ts, package.json): npm module declaration file to help with ts

---

lib/evervault.d.ts

Incorrect type for `cageAttestationData` , typos
Corrected type, fixes typos

fix: correct enableCagesBeta type

---

README.md
lib/config.js
lib/core/http.js
lib/evervault.d.ts
lib/index.js
lib/utils/errors.js
lib/utils/validationHelper.js
tests/client.test.js
tests/config.test.js
tests/core/http.test.js
tests/utils/validationHelper.test.js

We are introduce a new decrypt feature that allows the SDK to decrypt data. We are also starting requiring the APP ID along with the API key when initiating the SDK.
The following changes have been implemented:
- Expose a new function `decrypt` that allows Evervault's users to decrypt data
- Require the App ID when initiating the SDK

feat(decrypt function): Add decrypt functionality

---

README.md
lib/config.js
lib/core/http.js
lib/evervault.d.ts
lib/index.js
lib/utils/errors.js
lib/utils/validationHelper.js
tests/client.test.js
tests/config.test.js
tests/core/http.test.js
tests/utils/validationHelper.test.js

This reverts commit f2282d1813f432cf5977579c84483d684a9e820c.
Add a short description about this PR.
Add links to issues, tech plans etc.

fix: Revert "feat(decrypt function): Add decrypt functionality (#125)"

---

README.md
lib/config.js
lib/core/http.js
lib/evervault.d.ts
lib/index.js
lib/utils/errors.js
lib/utils/validationHelper.js
tests/client.test.js
tests/config.test.js
tests/core/http.test.js
tests/utils/validationHelper.test.js

BREAKING CHANGE: The App ID is now required when initialising the SDK
* feat(decrypt function): this adds the decrypt functionality
* fix: just a few improvements
* fix: fixes tests
* fix: update typedef
* feat: update url to decrypt endpoitn
* feat: allow primitive types to be decrypted
* feat: add support of file encryption
* feat: file decryption
* feat: update docs
* feat: error handling
* feat: change init order
* feat: fix tests
* feat: readme
* feat: decrypt Function
BREAKING CHANGE: The App ID is now required when initialising the SDK
Add a short description about this PR.
Add links to issues, tech plans etc.

feat!: Add decrypt functionality (#125)

---

README.md
lib/core/http.js
lib/evervault.d.ts
lib/index.js
lib/utils/errors.js
tests/core/http.test.js

Need to support the creation of client side decrypt tokens in the Node JS SDK
Add a function to create these tokens

feat(tokens): adds support for token creation to the SDK

---

.changeset/fair-planes-turn.md
package.json

Update changeset to release
Update

Add changeset: Cages GA attestation

---

.changeset/orange-rats-hunt.md
lib/index.js
tests/client.test.js

Removing deprecated logic ahead of upcoming major version bump
Removed intercept and ignore domains

Deprecating intercept and ignore domains

---

.changeset/wet-rivers-protect.md
.github/workflows/e2e.yml
e2e/function.test.js
lib/config.js
lib/core/http.js
lib/core/labs.js
lib/index.js
lib/utils/errors.js
lib/utils/validationHelper.js
package-lock.json
package.json
tests/client.test.js
tests/config.test.js
tests/core/http.test.js
tests/errors.test.js

Moving to the new endpoint will give us better error messages and clearer responses generally
Moved endpoint to `api.evervault.com/functions/FUNCTION_NAME/runs`
Also took the opportunity to deprecate encryptAndRun, async Function run requests, and specifying version of Function to run.

Using new Function run endpoint

---

.changeset/many-hairs-bathe.md
.changeset/orange-rats-hunt.md
.changeset/smooth-apes-roll.md
.changeset/wet-rivers-protect.md

The original changeset messages were not clear enough for user consumption
Updated changeset messages

Increasing clarity in changeset

---

.changeset/lucky-boxes-decide.md
lib/curves/asn1.js
lib/curves/base.js
package-lock.json
package.json

The `uasn1` dependency contains a telemetry postinstall script. We should remove it.

remove uasn1 dependency

---

.github/workflows/e2e.yml
.github/workflows/test.yml

Seperate matrix for e2e tests
Running tests twice per push
Made changes to the runner

update tests runner

---

.changeset/loud-shoes-flow.md
e2e/encryptDecrypt.test.js
lib/config.js
lib/core/crypto.js
lib/utils/errors.js

File encryption with data roles is a deprecated feature
Remove support for Data Policies from File Encryption

feat: remove data policies from file encryption

---

.changeset/famous-items-teach.md
e2e/encryptDecrypt.test.js
lib/core/crypto.js

This path isn't used anymore
Remove it

remove dead code
