.gitignore
lib/utils/datatypes.js
tests/datatypes.test.js

SDK explodes when parsing `null`.
Add `isDefined` check on array traversal to stop this happening and add test for it.
```
(node:3565) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'constructor' of null
at Object.isArray (/Users/eoinboylan/ev/snippets/ev-node-snippet/node_modules/@evervault/sdk/lib/utils/datatypes.js:1:32)
at _traverseObject (/Users/eoinboylan/ev/snippets/ev-node-snippet/node_modules/@evervault/sdk/lib/core/crypto.js:36:26)
at _traverseObject (/Users/eoinboylan/ev/snippets/ev-node-snippet/node_modules/@evervault/sdk/lib/core/crypto.js:33:38)
at async _encryptObject (/Users/eoinboylan/ev/snippets/ev-node-snippet/node_modules/@evervault/sdk/lib/core/crypto.js:19:12)
at async Object.encrypt (/Users/eoinboylan/ev/snippets/ev-node-snippet/node_modules/@everv …
```

Add null check to isArray

---

lib/utils/deploy.js

Deploy file required itself, and looked for a function (`deploy`) which did not exist.
Delete cyclic dependency

Remove cyclic dependency

---

.github/workflows/release.yml
package.json

To avoid having to manually run `npm publish` from authenticated machines.

Add Action to deploy automatically with semver

---

README.md
lib/config.js
lib/index.js
package-lock.json
tests/core/http.test.js

Gives user ability to pass in a list of domains they don't want to use with Outbound Relay. Requests to cages will also not be sent through Outbound Relay.
```javascript
{ relay: true , ignoreDomains: ['httpbin.org, www.facebook.com'] }
// requests sent to urls such as https://httpbin.org/post or https://api.facebook.com will not be sent through Relay
```

Add ignore domains to Node SDK and ignore cage requests

---

README.md
lib/index.js

Easier for users to integrate their API with Evervault. Just point Relay at the API, and initialize the SDK in the API.
The user can set `{ intercept: false }` when initializing to turn it off.

Default outbound Relay to ON in Node SDK

---

lib/core/http.js

Certain errors such as socket hangups can be retried client side.
Approach for if it fails is just to try again, and only error if that doesn't work too

Retry getting the CA if it fails once

---

lib/index.js

We previously changed the interface for disabling relay, but the change was not backwards compatible.
Made sure that both `intercept !== false` and `relay !== false` holds before overriding the HTTP requests.

Fix SDK backwards compatibility

---

lib/config.js
tests/config.test.js

Support custom non production endpoints for development and load testing
Check for the presence of EV_API_URL and EV_CAGE_RUN_URL else use the default production values

Support overrides of evervault endpoints via env variables

---

.github/pull_request_template.md

Ensure people have access to the semantic-release documentation and commit messages are in the correct format
Add to PR template

Add semantic-release info to PR template

---

lib/index.js

CA requests shouldn't be going through relay
Added the CA to the ignore domains list

fix(relay): CA request shouldn't go through Relay

---

.husky/commit-msg
.husky/prepare-commit-msg
CONTRIBUTING.md
README.md
commitlint.config.js
package-lock.json
package.json

We have semantic release enabled, which requires a certain style of commit. Previously this was enforced manually and loosely, and plenty of PRs had to be done which just made a silly change but had the correct commit style. 
This PR brings in two things:
- Commitizen, which will replace `git commit` with an interactive prompt to select the correct commit message. 
- Commitlint, which will run using Husky to ensure that commits are in the correct format (even if say they are not done through commitizen)

Enforce a consistent commit style compatible with Semantic Release

---

lib/core/http.js

There was a typo
Removed the typo

Fix Typo in Cert Fetching Retry Code

---

lib/index.js

We were checking for `instanceof string`, which should be `instanceof String`
Fix typo
We use [semantic-release](https://github.com/semantic-release/semantic-release#how-does-it-work) for deployments. If one of your commits should be deployed, ensure the commit message is in the format corresponding to the correct release type. This can also be done in a squash commit.
Note: breaking changes should always use the `BREAKING CHANGE:` commit message format.

fix(relay): Typo for string type in _isIgnoreRequest

---

lib/core/crypto.js
lib/core/http.js
lib/index.js

To better support our SDK development, we need to have some insight on how the SDKs are getting used.
This PR adds a non-blocking metrics reporter (runs asynchronously). This will batch encrypt metric notifications and run periodically. If the application is going to exit and some metrics have still not been reported, then that is done.

Add Encrypt Metrics Reporting

---

.github/pull_request_template.md

For semantic release to work and for change-logs to be generated correctly for our users, commits must be formatted as per [the convention](https://www.conventionalcommits.org/en/v1.0.0/). While there is a git hook to enforce this, for quick fixes it might be forgotten.
Added a checklist to the PR template

Add a checklist for commit message formatting

---

lib/utils/errors.js
package.json
tests/client.test.js

With the rollout of new error types from the Cage run API, need to reflect the errors in the SDKs.
If the error matches one of our known types (DecryptError or ForbiddenIPError) then surface that error.

Add DecryptError and ForbiddenIPError to JS SDK

---

lib/config.js
lib/index.js
tests/core/crypto.test.js

- Allow users to add a `curve` to client configuration options. Default to `secp256k1` if no curve is provided for backwards compatibility. 
- We will need to send a note (in whatever form) to customers to let them know we're moving to a new curve in the future

feat: add option for p256 curve while defaulting to secp256k1 curve

---

lib/index.js

config should be set before curve
Curve being set before the config. The curve setting logic relies on the config.

fix: reorder constructor

---

lib/index.js

key refresh function was always using the public key for the secp256k1 curve causing encryption with
prime256v1 to fail
key refresh function was always using the public key for the secp256k1 curve causing encryption with
prime256v1 to fail

fix: use correct ecdh key based on specified curve

---

lib/index.js
lib/utils/certHelper.js
lib/utils/index.js

The approach we were using for parsing x509 certificates only support node post v15.6.0.
Add support for older node versions in a cert helper module. If node crypto doesn't export an X509Certificate class, fallback to using the tls and net modules to parse the cert.

Add x509 parse function which supports node pre v15

---

README.md
lib/index.js
package-lock.json
package.json
tests/client.test.js

Add a short description about this PR.
Add links to issues, tech plans etc.
Changes the behaviour of outbound relay to instead use the decryptionDomains config option.
Warning: this is a breaking change. Will need to be published as a new major version.

feat!: update Node.js SDK to use 'decryptionDomains' config option

---

README.md

Cagify isn't functional and shouldn't be used.
Remove references to it

fix: removing deprecated feature

---

package.json

Mocha contained vulnerabilities that needed to be patched.
- Bump to version `^10.0.0`

fix: bump mocha to newest version

---

lib/index.js

Bug highlighted when using `node-fetch` with Evervault Outbound Interception, `node-fetch` formats its request to `https.request()` as an array which is currently unsupported by the filtration logic in outbound. 
Added a check for if the first argument is a string, if it is it will attempt to parse it as a string.

fix: fixed outbound for when args is an array

---

lib/index.js

Reverts evervault/evervault-node#97 as refactor doesn't trigger a release

Revert "refactor: debug log output will now contain an Evervault identifier"

---

lib/index.js

Its hard to distinguish Evervault debug logs from other libraries
- Add `EVERVAULT DEBUG ::` to distinguish them

fix: debug log output will now contain an Evervault identifier

---

lib/index.js

There are errors in Lambda when pulling configs from Cloudfront
- Add error message to the debug logs

fix: add error to debug log for outbound config request

---

lib/index.js

Decryption domains should not be on the deprecated list
- Removed as deprecated option

feat: remove decryption domains from the deprecation list

---

README.md
lib/index.js
lib/utils/validationHelper.js

The README & Client API still used the Cage product name. 
The following changes have been implemented:
- Rename `cage` API arguments to `function`
- Marked deprecated client methods as deprecated
- Update README

refactor(sdk): README & API cleanup

---

.github/workflows/release.yml

Semantic release bot only runs on node >= 18 and we were using node 14.
Bumped the version of node in the workflow

chore: bump version of node bot in release workflow

---

package-lock.json
package.json

Attestation bindings platform support was inaccurate in previous version causing a 404 on certain platforms.
Use latest attestation bindings with descoped platform support

fix(cageattestation): update attestation bindings to 0.1.0-alpha.3

---

lib/core/http.js
lib/utils/validationHelper.js

Functions should be able to be run using run tokens without pre-approved payloads
Add a check to the payload validator to also allow null or undefined payloads

feat(payloadvalidator): allow null or undefined runtoken payloads

---

lib/config.js
lib/core/crypto.js
lib/utils/errors.js
tests/core/crypto.test.js

We do not support decryption of files >25MB so an error should be thrown if an attempt is made to encrypt a file larger than this size
Added a max file size, compared the file size with this max

feat: throw error on file size too large

---

lib/core/crypto.js
lib/utils/crc32.js
package-lock.json
package.json
tests/core/crypto.test.js

Need to add crc32 sum for file encryption so that integrity can be checked on files
Added the crc32 sum calculation and bumped the versions

feat: calculate crc32 sum for files

---

README.md

We made updates to the Node SDK to allow users to use a list of sets of PCRs when attesting their Cage (https://github.com/evervault/evervault-node/pull/120) 
Add info about change

docs(cages attestation): document changes which allow users to provide a list of sets of PCRs

---

lib/utils/cageAttest.js
lib/utils/errors.js

If incorrect PCRs were provided to the Cage attestation client, the resulting error could not be caught. This was due to the error being thrown within the `checkServerIdentity` override, where it should have been returned.
Update error shape to match node spec. Return error instead of throwing.

fix(cageattestation): correct attested tls connection behaviour

---

lib/utils/cageAttest.js

Attestation bindings were required on hot code paths, which is unnecessary. We can require them at the top level, and then check that the bindings are not null on hot paths.
Load attestation bindings at top level.

fix(cageattest): split out require of attestation bindings

---

lib/core/http.js
tests/core/http.test.js

From a serverless function the SDK is receiving 502's from the CDN when retrieving the App's public key.
- Add a function to retry a max of 3 times, each time double the time between requests.

feat: adding retries to getting apps key

---

lib/evervault.d.ts

Update  interface for enableCagesBeta in `evervault.d.ts` so that you can pass an array of PCR document objects, or just a single one
* `lib/utils/cageAttest.js:55-60` (`function attestCageConnection(hostname, cert, cagesAttestationInfo = {}){...}`) handles the PCR document passed in to the `enableCagesBeta` function. 
* if only a single set of PCRs is passed in for a cage, the object containing the set of PCRs is wrapped in an array. If an array of PCRs is passed it, no change is made. 
* This means that for a given cage, either a single object containing PCRs can be passed in to `enableCagesBeta`, or an array of objects containing PCRs may be passed in. 
* **However**, the typescript interface in `evervault.d.ts` defines an interface that does not allow for an array of objects …

Fix typescript interface for `enableCagesBeta` in evervault.d.ts

---

README.md
lib/evervault.d.ts
lib/index.js
lib/utils/httpsHelper.js
lib/utils/proxyAgent.js
package-lock.json
package.json
test.js
tests/proxy.test.js

When using the `enableOutboundRelay` it is currently not possible to configure Relay to send traffic to a single path on a domain. Instead all traffic will go to a configured Relay destination.
- Add a new method `createRelayHttpsAgent` which will return a pre configured https agent. This agent can be passed to supporting HTTP clients to send specific requests through a Relay.

feat: add createRelayHttpsAgent to return configured https agent

---

.github/workflows/e2e.yml
e2e/encryptDecrypt.test.js
e2e/function.test.js
e2e/outboundRelay.test.js
lib/core/http.js
package-lock.json
package.json
tests/client.test.js

- Developing the Node.js SDK required a lot of manual testing. Automated end-to-end tests were badly needed.
This PR introduces the following changes:
- Add e2e tests to validate encryption & decryption, function runs & outbound relay proxying
- Add github workflow to automatically trigger e2e tests when pushing a change
- Fix a bug with the handling of async Function runs:
- Async runs would return an empty `Buffer` as a response which was failing when `phin` tried to parse it as JSON

chore(e2e_tests): Add e2e tests

---

.github/workflows/release.yml

Error on release:
> The value of the GITHUB_TOKEN environment variable is being used for authentication.
> To have GitHub CLI store credentials instead, first clear the value from the environment.
Removed set of `GITHUB_TOKEN`

Removing set of github token in release workflow

---

.github/workflows/release.yml

`npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/`
Added auth per [docs](https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow)

Setting npm token

---

.changeset/dirty-mangos-swim.md
lib/config.js
lib/core/attestationDoc.js
lib/core/http.js
lib/core/index.js
lib/core/pcrManager.js
lib/evervault.d.ts
lib/index.js
lib/utils/attest.js
lib/utils/errors.js
lib/utils/index.js
tests/attestationDoc.test.js
tests/pcrManager.test.js
tests/utils/attest.test.js
tests/utils/attestGA.test.js

Update NodeSDK to have new enclave functions, and deprecate old cage functions
- Update client to have enclave attestation entrypoints exposed
- Add deprecation notice to cage functions
- Make file names more generic, update tests

Add enclave functions to node sdk

---

.changeset/rare-olives-promise.md
lib/index.js
lib/utils/attest.js

Attestation doc cache was receiving a child of the config on the enableEnclaves entrypoint, but expected the entire config to be provided (as was the case for enableCages). This led to an undefined reference when creating the attestation doc cache.
- Pass the correct config
- Correct validation on the attestation measures.

Patch config object passed to attestation doc cache through enableEnclaves entrypoint

---

.changeset/shy-zebras-hunt.md
lib/index.js

Incorrect config provided to PCR Manager in enableEnclaves function
Pass `this.config` as the config is a builder pattern

Patch pcr manager

---

.changeset/great-snakes-doubt.md
lib/config.js
lib/utils/attest.js

The attestation listener was missing the enclaves hostname.
Update to add the enclaves hostname.
Also update the Beta attestation listener to use cagesBetaHostname

Add enclaves hostname to attestation listener

---

.changeset/breezy-garlics-beg.md
lib/evervault.d.ts
lib/utils/attest.js

The validation used on the parameters given to enableEnclaves is incorrect - it does not allow for callbacks to be given as values in the map. The typings were also incorrect, showing that a nested record was supported.
Correct typings - only advertise support for an object of PCRs, a list of objects of PCRs or functions as values in the map.
Correct validation - allow functions to be given as values.

fix: correct typings for enableEnclaves, and fix validation function to allow callbacks

---

.changeset/rich-comics-divide.md
e2e/outboundRelay.test.js
lib/core/attestationDoc.js
lib/core/pcrManager.js
lib/core/relayOutboundConfig.js
lib/core/repeatedTimer.js
lib/evervault.d.ts
lib/index.js
package.json
tests/client.test.js

SDK instances which make use of the RepeatedTimer module will prevent NodeJS processes from exiting by remaining scheduled in the event loop.
Update the RepeatedTimer module to make the intervals headless using the `unref` function from the node Timer type. This will allow Node processes to exit cleanly without waiting for the interval to shutdown.
This PR also introduces a `_backgroundJobs` array on the Node SDK which tracks all open intervals, and allows users to explicitly shut them down using the `shutdown` function.

Make repeated timers headless

---

.changeset/honest-seahorses-grow.md
lib/core/pcrManager.js

Utility functions within the PCR Manager were incorrectly declared.
Declare the functions as consts.

Resolve reference error in PCR manager

---

.changeset/rotten-singers-check.md
CHANGELOG.md
package.json

Reverts evervault/evervault-node#179
The tsc command for generating our types needs to be updated to avoid errors in a dependency's typing file.

Revert "New Release"

---

package.json

Latest release is failing to publish due to a typing error in our `agent-base` dependency. It currently imports several node libs as a default, `import net from "net";` instead of using the more correct `import * as net from "net";`.
Allow synthetic default imports

Add flag to tsc call to support synthetic default imports

---

.github/workflows/test.yml
lib/utils/httpsHelper.js
lib/utils/proxyAgent.js
tests/httpHelper.test.js

Want to test against more recent versions of Node
Update test matrix
Remove the conditional perform attestation thing because it should work on all new supported Node versions

update the matrix

---

.changeset/metal-moles-give.md
lib/config.js
lib/index.js
lib/utils/attest.js

Provide a method to create an `EnclaveAgent` which can be passed to a HTTP lib (like axios) for attesting requests. This allows for more control over which requests are attested than the enableEnclaves function which attempts to attest any `.enclaves.evervault.com`.
The SDK now provides an async method `createEnclaveHttpsAgent` which kicks off background polling for Enclave attestation documents and PCR from supplied PCR providers. It then returns an extension of the `https.Agent` class called EnclaveAgent. This can be passed to http libs. It overrides the `checkServerIdentity` method to provide Enclave attestation during a TLS handshake.
```javascript
const evervault = new Evervault('app_uuid', 'ev:key...');
const enclaveHttpsAgent = await evervault.createEnclaveHttpsAgent({ …
```

[ETR-2357] Add createEnclaveHttpsAgent for attesting connections to enclave

---

.changeset/friendly-ladybugs-know.md
lib/core/http.js

Incorrect header name is causing validation errors
- get keys with `x-evervault-app-id` header

fix: app uuid header is incorrect

---

.changeset/green-teachers-flow.md
lib/core/http.js
lib/index.js
lib/utils/errors.js
package.json
tests/client.test.js
tests/core/http.test.js
tests/httpHelper.test.js

`phin` is unmaintained. We considered using `got`, but it only supports the ESM module system and migrating the repo to that would be scope creep. We also considered using `fetch` but native `fetch` doesn't work with some parts of the code for outbound relay and we would end up relying on axios anyway.
Replace phin code with axios equivalents.

Replace phin with axios as phin is unmaintained

---

.changeset/tiny-years-bake.md
e2e/outboundRelay.test.js
lib/config.js
lib/core/http.js
lib/index.js
lib/types.d.ts
lib/utils/domainTargets.d.ts
lib/utils/domainTargets.js
lib/utils/httpsHelper.js
lib/utils/index.js
package.json
tests/utils/domainTargets.test.js

We want to extend support for request filtering when sending via forward proxy to account for the path if specific on the decryptionDomains.
- Add domainTarget which builds a small 'target' object from the provided list of domains. The target object wraps the ability to match a request based on hostname and optionally target
- Update all request intercept logic to include the domain and path
- Update the jsdoc typing comments to be more accurate.
- Tidy up some unused code

feat: add support for including target path in request filtering

---

.github/workflows/release.yml

Action is failing to publish, and unclear where the token in use has come from.
Use common token for release

Update sdk publish token

---

.changeset/few-beers-draw.md
lib/utils/httpsHelper.js
tests/httpHelper.test.js

Bug introduced in https://github.com/evervault/evervault-node/pull/206
It wasn't handling `.path` which is happening for us, and it seems node request supports
And also noticed for the `Url` case it was returning `host` instead of `domain` so would be ignored 🙈

Fix extracting domain from url

---

.changeset/modern-jeans-wave.md
e2e/encryptDecrypt.test.js
lib/core/http.js

Without passing a response type, axios assumes that responses contain json. This is causing decrypted files to be corrupted when returned from the SDK.
Pass response type to the decrypt post request as `arraybuffer` for files, so we can return the raw octet stream

Pass response type to axios for file decrypt requests
